// <auto-generated />
using System;
using BeforeOutTime.Repository.Dbs.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeforeOurTime.Business.Migrations.MSSQL
{
    [DbContext(typeof(MSSQLContext))]
    [Migration("20180930064059_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Characters.CharacterAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AttributeType");

                    b.Property<Guid?>("HealthId");

                    b.Property<Guid>("ItemId");

                    b.HasKey("Id");

                    b.HasIndex("HealthId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Item_Attribute_Characters");
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Characters.CharacterHealth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Max");

                    b.Property<int>("Value");

                    b.HasKey("Id");

                    b.ToTable("Item_Attribute_Characters_Health");
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Exits.ExitAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("DestinationLocationId");

                    b.Property<int>("Effort");

                    b.Property<Guid>("ItemId");

                    b.Property<string>("Name");

                    b.Property<int>("Time");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Item_Attribute_Exits");

                    b.HasDiscriminator().HasValue("ExitAttribute");
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Physicals.PhysicalAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Depth");

                    b.Property<string>("Description");

                    b.Property<int>("Height");

                    b.Property<Guid?>("ImageIconId");

                    b.Property<Guid>("ItemId");

                    b.Property<string>("Name");

                    b.Property<int>("Weight");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.HasIndex("ImageIconId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Item_Attribute_Physicals");

                    b.HasDiscriminator().HasValue("PhysicalAttribute");
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Players.PlayerAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountId");

                    b.Property<Guid>("ItemId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Item_Attribute_Players");

                    b.HasDiscriminator().HasValue("PlayerAttribute");
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Visibles.VisibleAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid?>("IconId");

                    b.Property<Guid>("ItemId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Item_Attribute_Visibles");

                    b.HasDiscriminator().HasValue("VisibleAttribute");
                });

            modelBuilder.Entity("BeforeOurTime.Models.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ParentId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BeforeOurTime.Models.Modules.Core.Models.Data.LocationData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DataItemId");

                    b.Property<string>("DataType");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LocationData");
                });

            modelBuilder.Entity("BeforeOurTime.Models.Primitives.Images.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Base64");

                    b.Property<bool>("Gzipped");

                    b.Property<int>("Location");

                    b.Property<int>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Characters.CharacterAttribute", b =>
                {
                    b.HasOne("BeforeOurTime.Models.ItemAttributes.Characters.CharacterHealth", "Health")
                        .WithMany()
                        .HasForeignKey("HealthId");

                    b.HasOne("BeforeOurTime.Models.Items.Item", "Item")
                        .WithOne()
                        .HasForeignKey("BeforeOurTime.Models.ItemAttributes.Characters.CharacterAttribute", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Exits.ExitAttribute", b =>
                {
                    b.HasOne("BeforeOurTime.Models.Modules.Core.Models.Data.LocationData", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeforeOurTime.Models.Items.Item", "Item")
                        .WithOne()
                        .HasForeignKey("BeforeOurTime.Models.ItemAttributes.Exits.ExitAttribute", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Physicals.PhysicalAttribute", b =>
                {
                    b.HasOne("BeforeOurTime.Models.Primitives.Images.Image", "ImageIcon")
                        .WithMany()
                        .HasForeignKey("ImageIconId");

                    b.HasOne("BeforeOurTime.Models.Items.Item", "Item")
                        .WithOne()
                        .HasForeignKey("BeforeOurTime.Models.ItemAttributes.Physicals.PhysicalAttribute", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Players.PlayerAttribute", b =>
                {
                    b.HasOne("BeforeOurTime.Models.Items.Item", "Item")
                        .WithOne()
                        .HasForeignKey("BeforeOurTime.Models.ItemAttributes.Players.PlayerAttribute", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BeforeOurTime.Models.ItemAttributes.Visibles.VisibleAttribute", b =>
                {
                    b.HasOne("BeforeOurTime.Models.Primitives.Images.Image", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.HasOne("BeforeOurTime.Models.Items.Item", "Item")
                        .WithOne()
                        .HasForeignKey("BeforeOurTime.Models.ItemAttributes.Visibles.VisibleAttribute", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeforeOurTime.Models.Items.Item", b =>
                {
                    b.HasOne("BeforeOurTime.Models.Items.Item", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
