// <auto-generated />
using System;
using BeforeOurTime.Business.Modules.Script.Dbs.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeforeOurTime.Business.Migrations.EFScriptModule
{
    [DbContext(typeof(EFScriptModuleContext))]
    [Migration("20190103235636_javascript-item-data")]
    partial class javascriptitemdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeforeOurTime.Models.Modules.Script.ItemProperties.Javascripts.JavascriptItemData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DataBag");

                    b.Property<Guid>("DataItemId");

                    b.Property<string>("Script");

                    b.HasKey("Id");

                    b.ToTable("Item_Data_Javascripts");
                });
#pragma warning restore 612, 618
        }
    }
}
